font:

  normal:
    family: MesloLGM Nerd Font
    style: Regular

  bold:
    family: MesloLGM Nerd Font
    style: Bold

  italic:
    family: MesloLGM Nerd Font
    style: Italic

  bold_italic:
    family: MesloLGM Nerd Font
    style: Bold Italic

  size: 15
  offset:
    x: 0
    y: -2

  draw_bold_text_with_bright_colors: false
window:
  padding:
    x: 14
    y: 14

key_bindings:
  - { key: Key3,     mods: Alt, chars: "#" }
  - { key: PageUp,   mods: Shift, action: ScrollPageUp }
  - { key: PageDown, mods: Shift, action: ScrollPageDown }
  - { key: End,      mods: Shift, action: ScrollToBottom }
  - { key: Home,     mods: Shift, action: ScrollToTop }
  - { key: Key0,     mods: Command, action: ResetFontSize }
  - { key: Equals,   mods: Command, action: IncreaseFontSize }
  - { key: Minus,    mods: Command, action: DecreaseFontSize }
  - { key: N,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }

# Colors (Dark plus)
colors:
  primary:
    background: '0x1E1E1E'
    foreground: '0xD4D4D4'

  normal:
    black:   '0x1E1E1E'
    red:     '0xF44747'
    green:   '0x608B4E'
    yellow:  '0xD7BA7D'
    blue:    '0x569CD6'
    magenta: '0xC586C0'
    cyan:    '0x9CDCFE'
    white:   '0xD4D4D4'
