#! /bin/sh

xrdb ~/.Xresources
setxkbmap uk
xsetroot -cursor_name left_ptr
xrandr --output HDMI-1 --primary --preferred
feh --bg-scale ~/.config/wallpapers
xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &
picom -b --config ~/.config/picom/picom.conf
polybar top &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#333333"
bspc config focused_border_color "#111111"

