#! /bin/sh

xrdb ~/.Xresources
setxkbmap uk
xsetroot -cursor_name left_ptr
xrandr --output LVDS-1 off
feh --bg-scale ~/.config/wallpapers
xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
