window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true

font:
  normal:
    family: MesloLGM Nerd Font
    style: Regular
  bold:
    family: MesloLGM Nerd Font
    style: Bold
  italic:
    family: MesloLGM Nerd Font
    style: Italic
  bold_italic:
    family: MesloLGM Nerd Font
    style: Bold Italic
  size: 14.0
  offset:
    x: 0
    y: -2

  draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: F11, mods: Shift, action: ToggleFullscreen }
  - { key: Escape, mods: Shift, action: Quit }

colors:
  primary:
    background: '0x1E1E1E'
    foreground: '0xD4D4D4'

  normal:
    black:   '0x1E1E1E'
    red:     '0xF44747'
    green:   '0x608B4E'
    yellow:  '0xD7BA7D'
    blue:    '0x569CD6'
    magenta: '0xC586C0'
    cyan:    '0x9CDCFE'
    white:   '0xD4D4D4'

# Colors (Solarized Dark)
#colors:
#  # Default colors
#  primary:
#    background: '0x002b36'
#    foreground: '0x839496'
#
#  # Normal colors
#  normal:
#    black:   '0x073642'
#    red:     '0xdc322f'
#
#    green:   '0x859900'
#    yellow:  '0xb58900'
#    blue:    '0x268bd2'
#    magenta: '0xd33682'
#    cyan:    '0x2aa198'
#    white:   '0xeee8d5'
#
#  # Bright colors
#  bright:
#    black:   '0x002b36'
#    red:     '0xcb4b16'
#    green:   '0x586e75'
#
#    yellow:  '0x657b83'
#    blue:    '0x839496'
#    magenta: '0x6c71c4'
#    cyan:    '0x93a1a1'
#    white:   '0xfdf6e3'

